"use client";
import { useMemo, useState } from "react";
import { Camera, CheckCircle2, CircleAlert, Search, Trash2, X } from "lucide-react";
import { useDemoStore } from "@/lib/demo-store";
import type { ProblemItemStatus } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input, Label, Select } from "@/components/ui/field";

export function ProblemItemsPanel() {
  const store = useDemoStore(); const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const filtered = useMemo(() => store.problemItems.filter((x) => [x.description, x.packagingNotes, x.readableName, x.readableAddress].join(" ").toLowerCase().includes(search.toLowerCase())), [store.problemItems, search]);
  return <div className="space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-extrabold">Barang Problem</h2><p className="text-sm text-slate-500">Pencatatan khusus admin untuk kiriman tanpa resi atau alamat terlepas.</p></div><Button onClick={() => setOpen(true)}><Camera className="h-4 w-4" /> Catat Barang</Button></div><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input className="pl-9" placeholder="Cari isi, nama, alamat, atau ciri kemasan..." value={search} onChange={(e) => setSearch(e.target.value)} /></div>{!filtered.length ? <Card><CardContent className="py-14 text-center text-sm text-slate-500">Belum ada data barang problem.</CardContent></Card> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <ProblemCard key={item.id} item={item} onDelete={async () => { if (confirm("Hapus data barang ini?")) await store.deleteProblemItem(item.id); }} onStatus={(status) => store.updateProblemItem(item.id, { status })} />)}</div>}{open && <ProblemForm onClose={() => setOpen(false)} busy={busy} setBusy={setBusy} error={error} setError={setError} />}</div>;
}
function ProblemCard({ item, onDelete, onStatus }: { item: any; onDelete: () => Promise<void>; onStatus: (status: ProblemItemStatus) => Promise<void> }) { return <Card className="overflow-hidden"><img src={item.photo} alt="Foto barang problem" className="h-48 w-full bg-slate-100 object-cover" /><CardContent className="space-y-3 p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-extrabold">{item.description}</p><p className="text-xs text-slate-500">Masuk {item.receivedAt}</p></div><span className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-700">{item.status}</span></div><p className="text-sm text-slate-600"><b>Kemasan:</b> {item.packagingNotes}</p>{item.readableName && <p className="text-sm text-slate-600"><b>Terbaca:</b> {item.readableName}</p>}{item.readableAddress && <p className="text-sm text-slate-600"><b>Alamat:</b> {item.readableAddress}</p>}<div className="flex gap-2 border-t pt-3"><Select className="h-9 flex-1 text-xs" value={item.status} onChange={(e) => void onStatus(e.target.value as ProblemItemStatus)}><option value="DICARI">Sedang dicari</option><option value="DITEMUKAN">Ditemukan</option><option value="SELESAI">Selesai</option></Select><Button size="sm" variant="ghost" className="text-red-600" onClick={() => void onDelete()}><Trash2 className="h-4 w-4" /></Button></div></CardContent></Card> }
function ProblemForm({ onClose, busy, setBusy, error, setError }: any) { const store = useDemoStore(); const [photo, setPhoto] = useState(""); const [description, setDescription] = useState(""); const [receivedAt, setReceivedAt] = useState(new Date().toISOString().slice(0, 10)); const [packagingNotes, setPackagingNotes] = useState(""); const [readableName, setReadableName] = useState(""); const [readableAddress, setReadableAddress] = useState(""); const save = async () => { if (!photo || !description || !packagingNotes) return setError("Foto, isi barang, dan ciri kemasan wajib diisi."); setBusy(true); setError(""); try { await store.saveProblemItem({ photo, description, receivedAt, packagingNotes, readableName, readableAddress, status: "DICARI" }); onClose(); } catch (e) { setError(e instanceof Error ? e.message : "Gagal menyimpan data."); } finally { setBusy(false); } }; return <div className="fixed inset-0 z-[80] overflow-y-auto bg-slate-950/50 p-3 sm:p-8"><div className="mx-auto max-w-2xl rounded-2xl bg-white p-5"><div className="flex justify-between"><div><h3 className="text-xl font-extrabold">Catat Barang Problem</h3><p className="text-sm text-slate-500">Hanya dapat diakses admin.</p></div><button onClick={onClose}><X /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Foto barang / kemasan</Label><input type="file" accept="image/*" capture="environment" className="w-full rounded-xl border p-3 text-sm" onChange={(e) => { const file = e.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setPhoto(String(reader.result)); reader.readAsDataURL(file); }} />{photo && <img src={photo} alt="Preview" className="mt-2 h-40 w-full rounded-xl object-cover" />}</div><div><Label>Isi barang</Label><Input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Contoh: sepatu hitam" /></div><div><Label>Tanggal masuk</Label><Input type="date" value={receivedAt} onChange={(e) => setReceivedAt(e.target.value)} /></div><div className="sm:col-span-2"><Label>Ciri-ciri kemasan</Label><Input value={packagingNotes} onChange={(e) => setPackagingNotes(e.target.value)} placeholder="Kardus cokelat, lakban merah, robek di sisi kanan" /></div><div><Label>Nama yang masih terbaca</Label><Input value={readableName} onChange={(e) => setReadableName(e.target.value)} /></div><div><Label>Alamat yang masih terbaca</Label><Input value={readableAddress} onChange={(e) => setReadableAddress(e.target.value)} /></div></div>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={onClose}>Batal</Button><Button disabled={busy} onClick={() => void save()}>{busy ? "Menyimpan..." : "Simpan Data"}</Button></div></div></div> }
