"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import "leaflet/dist/leaflet.css";
import { Activity, CarFront, CheckCircle2, Clock3, LocateFixed, RefreshCw, Search, Users } from "lucide-react";
import { useDemoStore } from "@/lib/demo-store";
import { createClient } from "@/lib/supabase/client";

type Position = { log_id: string; latitude: number; longitude: number; accuracy: number; recorded_at: string; trip: { jam_akhir: string | null; driver: { nama: string } | null; vehicle: { plat_nomor: string } | null } | null };
type Status = "active" | "stale" | "finished";
const statusLabel = (status: Status) => status === "active" ? "Aktif" : status === "stale" ? "Terlambat" : "Selesai";
const initials = (name: string) => name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();

export function TrackingPanel() {
  const store = useDemoStore(); const [positions, setPositions] = useState<Position[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [now, setNow] = useState(Date.now()); const [selected, setSelected] = useState(""); const [query, setQuery] = useState(""); const [statusFilter, setStatusFilter] = useState<"all" | Status>("all"); const [activeOnly, setActiveOnly] = useState(false);
  const mapRef = useRef<HTMLDivElement>(null); const leafletRef = useRef<{ map: import("leaflet").Map; layer: import("leaflet").LayerGroup } | null>(null); const getStatus = useCallback((point: Position): Status => point.trip?.jam_akhir ? "finished" : now - Date.parse(point.recorded_at) > 120000 ? "stale" : "active", [now]);
  useEffect(() => { const client = createClient(); let cancelled = false; let timer: ReturnType<typeof setTimeout>; async function refresh() { try { if (!store.isRemote || !client) { setLoading(false); return; } const { data, error: fetchError } = await client.from("tracking_latest").select("log_id,latitude,longitude,accuracy,recorded_at,trip:vehicle_logs(jam_akhir,driver:users(nama),vehicle:vehicles(plat_nomor))").order("recorded_at", { ascending: false }).limit(200); if (fetchError) throw fetchError; if (!cancelled) { setPositions((data ?? []) as unknown as Position[]); setError(""); setNow(Date.now()); } } catch { if (!cancelled) setError("Posisi belum berhasil dimuat. Periksa koneksi dan migrasi tracking."); } finally { if (!cancelled) { setLoading(false); timer = setTimeout(refresh, 15000); } } } void refresh(); return () => { cancelled = true; clearTimeout(timer); }; }, [store.isRemote]);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 15000); return () => clearInterval(timer); }, []);
  const filtered = useMemo(() => positions.filter((point) => { const label = `${point.trip?.driver?.nama ?? ""} ${point.trip?.vehicle?.plat_nomor ?? ""}`.toLowerCase(); const status = getStatus(point); return (!query || label.includes(query.toLowerCase())) && (statusFilter === "all" || status === statusFilter) && (!activeOnly || status === "active"); }), [positions, query, statusFilter, activeOnly, getStatus]);
  const stats = { active: positions.filter((p) => getStatus(p) === "active").length, stale: positions.filter((p) => getStatus(p) === "stale").length, finished: positions.filter((p) => getStatus(p) === "finished").length };
  useEffect(() => { let cancelled = false; async function drawMap() { if (!mapRef.current) return; const L = await import("leaflet"); if (cancelled || !mapRef.current) return; if (!leafletRef.current) { const map = L.map(mapRef.current, { zoomControl: false }).setView([-6.2, 106.816666], 10); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { attribution: "© OpenStreetMap contributors", maxZoom: 19 }).addTo(map); leafletRef.current = { map, layer: L.layerGroup().addTo(map) }; } const { map, layer } = leafletRef.current; layer.clearLayers(); const bounds: [number, number][] = []; filtered.forEach((point) => { const status = getStatus(point); const color = status === "active" ? "#0da99d" : status === "stale" ? "#f59e0b" : "#64748b"; const icon = L.divIcon({ className: "movetra-marker", html: `<span style="background:${color}"><span>▰</span></span>`, iconSize: [38, 38], iconAnchor: [19, 19] }); L.marker([point.latitude, point.longitude], { icon }).on("click", () => setSelected(point.log_id)).addTo(layer); bounds.push([point.latitude, point.longitude]); }); if (bounds.length) map.fitBounds(bounds as import("leaflet").LatLngBoundsExpression, { padding: [30, 30], maxZoom: 13 }); } void drawMap(); return () => { cancelled = true; }; }, [filtered, getStatus]);
  useEffect(() => () => { leafletRef.current?.map.remove(); leafletRef.current = null; }, []);
  const chosen = filtered.find((point) => point.log_id === selected) ?? positions.find((point) => point.log_id === selected); const driverRows = filtered.filter((point) => getStatus(point) !== "finished").slice(0, 8);
  const metricCards = [{ Icon: CarFront, label: "Driver aktif", value: stats.active, color: "bg-teal-50 text-teal-700" }, { Icon: Clock3, label: "Terlambat", value: stats.stale, color: "bg-amber-50 text-amber-600" }, { Icon: CheckCircle2, label: "Perjalanan selesai", value: stats.finished, color: "bg-teal-50 text-teal-700" }, { Icon: Users, label: "Total terpantau", value: positions.length, color: "bg-blue-50 text-blue-600" }];
  return <section className="space-y-4 rounded-[1.25rem] bg-[#edf8f7] p-3 text-slate-900 sm:p-5">
    <div className="relative overflow-hidden rounded-2xl bg-gradient-to-r from-[#007c7e] via-[#079f98] to-[#11b5a9] px-6 py-5 text-white shadow-sm"><div className="relative z-10"><p className="text-xs font-semibold uppercase tracking-wider text-teal-100">Movetra · Live fleet control</p><h2 className="mt-1 text-2xl font-extrabold">Tracking driver</h2><p className="text-sm text-teal-50">Pantau posisi dan status armada secara real-time.</p></div><div className="absolute right-6 top-1/2 flex -translate-y-1/2 items-center gap-3 text-xs"><span className="rounded-full border border-white/30 px-4 py-2"><i className="mr-2 inline-block h-2 w-2 rounded-full bg-emerald-200" />Live</span><span className="hidden sm:inline">Update terakhir {new Date(now).toLocaleTimeString("id-ID")}</span></div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metricCards.map(({ Icon, label, value, color }) => <div key={label} className="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><span className={`grid h-12 w-12 place-items-center rounded-xl ${color}`}><Icon className="h-6 w-6" /></span><div><p className="text-sm text-slate-500">{label}</p><p className="text-2xl font-extrabold text-slate-900">{value}</p></div></div>)}</div>
    <div className="flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-4 top-3.5 h-5 w-5 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari driver atau nomor plat..." className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-11 pr-4 text-sm outline-none focus:border-teal-500" /></div><select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value as "all" | Status)} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600"><option value="all">Semua status</option><option value="active">Aktif</option><option value="stale">Terlambat</option><option value="finished">Selesai</option></select><button onClick={() => setActiveOnly(!activeOnly)} className={`rounded-xl border px-4 py-3 text-sm font-semibold ${activeOnly ? "border-teal-500 bg-teal-50 text-teal-700" : "border-slate-200 bg-white text-slate-600"}`}>{activeOnly ? "✓ Hanya aktif" : "Hanya aktif"}</button><button aria-label="Refresh" onClick={() => setNow(Date.now())} className="grid h-12 w-12 place-items-center rounded-xl border border-slate-200 bg-white text-slate-600"><RefreshCw className="h-5 w-5" /></button></div>
    {error && <p role="alert" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-700">{error}</p>}{loading && <p role="status" className="text-sm text-slate-500">Memuat posisi…</p>}
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.55fr)_minmax(370px,1fr)]"><div ref={mapRef} className="relative h-[520px] min-h-[420px] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="pointer-events-none absolute left-3 top-3 z-[400] rounded-xl bg-white p-2 shadow"><LocateFixed className="h-5 w-5 text-slate-600" /></div><div className="pointer-events-none absolute bottom-3 left-3 z-[400] rounded-xl bg-white px-4 py-3 text-xs shadow"><span className="mr-4"><i className="mr-1 inline-block h-2.5 w-2.5 rounded-full bg-teal-500" />Aktif ({stats.active})</span><span className="mr-4"><i className="mr-1 inline-block h-2.5 w-2.5 rounded-full bg-amber-500" />Terlambat ({stats.stale})</span><span><i className="mr-1 inline-block h-2.5 w-2.5 rounded-full bg-slate-500" />Selesai ({stats.finished})</span></div></div>
      <div className="space-y-4"><div className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex items-center justify-between px-2 pb-3"><h3 className="font-extrabold">Driver dipantau <span className="ml-1 rounded-full bg-teal-100 px-2 py-1 text-xs text-teal-700">{filtered.length}</span></h3><Activity className="h-5 w-5 text-teal-600" /></div><div className="mb-2 grid grid-cols-3 rounded-lg border border-slate-200 text-center text-xs font-semibold"><button onClick={() => setStatusFilter("all")} className={`p-2 ${statusFilter === "all" ? "rounded-lg bg-teal-100 text-teal-700" : "text-slate-500"}`}>Semua ({positions.length})</button><button onClick={() => setStatusFilter("active")} className="p-2 text-slate-500">Aktif ({stats.active})</button><button onClick={() => setStatusFilter("stale")} className="p-2 text-slate-500">Terlambat ({stats.stale})</button></div>{driverRows.map((point) => { const name = point.trip?.driver?.nama ?? "Driver"; const status = getStatus(point); return <button key={point.log_id} onClick={() => setSelected(point.log_id)} className={`flex w-full items-center gap-3 border-b border-slate-100 px-2 py-3 text-left last:border-0 ${selected === point.log_id ? "rounded-lg bg-teal-50" : ""}`}><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-slate-100 text-xs font-bold text-slate-700">{initials(name)}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{name}</b><small className="block truncate text-xs text-slate-500">{point.trip?.vehicle?.plat_nomor ?? "-"}</small></span><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${status === "active" ? "bg-teal-100 text-teal-700" : "bg-amber-100 text-amber-700"}`}>{statusLabel(status)}</span><small className="hidden text-[10px] text-slate-500 sm:block">{Math.max(0, Math.round((now - Date.parse(point.recorded_at)) / 1000))} detik</small></button>; })}</div>
        {chosen && <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h3 className="font-extrabold">Detail perjalanan</h3><div className="mt-3 grid grid-cols-3 gap-3 text-xs"><div><p className="text-slate-500">Driver</p><b>{chosen.trip?.driver?.nama ?? "Driver"}</b><p className="text-slate-500">{chosen.trip?.vehicle?.plat_nomor ?? "-"}</p></div><div><p className="text-slate-500">GPS diperbarui</p><b>{Math.max(0, Math.round((now - Date.parse(chosen.recorded_at)) / 1000))} detik lalu</b></div><a className="self-center rounded-lg bg-teal-600 px-3 py-2 text-center font-bold text-white" href={`https://www.google.com/maps?q=${chosen.latitude},${chosen.longitude}`} target="_blank" rel="noreferrer">Lihat detail →</a></div></div>}</div></div>
    {!store.isRemote && <p className="text-xs text-slate-500">Mode demo: belum ada lokasi GPS. Hubungkan akun Supabase untuk melihat tracking antarperangkat.</p>}
  </section>;
}
